[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
addopts = "-v"  # This replaces the verbose=true option
markers = [
    "asyncio: mark a test as an asyncio test",
    "slow: mark test as slow",
    "integration: integration tests that hit real resources"
]
log_cli = true
log_cli_level = "INFO"