"""Create todo_items table

Revision ID: 2717450a5d50
Revises: 
Create Date: 2025-08-21 15:50:27.644869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2717450a5d50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_items_description'), 'todo_items', ['description'], unique=False)
    op.create_index(op.f('ix_todo_items_id'), 'todo_items', ['id'], unique=False)
    op.create_index(op.f('ix_todo_items_title'), 'todo_items', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_items_title'), table_name='todo_items')
    op.drop_index(op.f('ix_todo_items_id'), table_name='todo_items')
    op.drop_index(op.f('ix_todo_items_description'), table_name='todo_items')
    op.drop_table('todo_items')
    # ### end Alembic commands ###
